// Generated by CoffeeScript 1.12.6
(function() {
  var TreeOne;

  TreeOne = require('../../src/js/tree-one');

  describe('TreeOne', function() {
    return describe('render', function() {
      return it('should render a view', function() {
        return assert.equal(0, 0);
      });
    });
  });

}).call(this);

//# sourceMappingURL=tree-one.js.map
