// Generated by CoffeeScript 1.12.6
(function() {
  var ExtendedMockNode, MockNode, Node, ViewTree, create, expectNode, expectTag, expectText, expectType,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ViewTree = require('../../src/js/view-tree');

  Node = ViewTree.Node;

  MockNode = (function(superClass) {
    extend(MockNode, superClass);

    function MockNode() {
      return MockNode.__super__.constructor.apply(this, arguments);
    }

    MockNode.prototype.render = function() {
      return {
        tag: 'mock-node'
      };
    };

    return MockNode;

  })(Node);

  ExtendedMockNode = (function(superClass) {
    extend(ExtendedMockNode, superClass);

    function ExtendedMockNode() {
      return ExtendedMockNode.__super__.constructor.apply(this, arguments);
    }

    return ExtendedMockNode;

  })(MockNode);

  ViewTree.map('mock', MockNode);

  create = ViewTree.create;

  expectNode = function(node, clazz) {
    if (clazz == null) {
      clazz = Node;
    }
    expect(node).to.be["instanceof"](clazz);
    return expect(node.view).to.be.ok;
  };

  expectType = function(node, type) {
    expectNode(node);
    return expect(node.view.nodeType).to.equal(type);
  };

  expectText = function(node, text) {
    expectType(node, 3);
    return expect(node.view.nodeValue).to.equal(text + '');
  };

  expectTag = function(node, tag) {
    expectType(node, 1);
    return expect(node.view.nodeName.toUpperCase()).to.equal(tag.toUpperCase());
  };

  describe('TreeOne', function() {
    return describe('create', function() {
      it('should throw an error if cfg is null or undefined', function() {
        expect(function() {
          return create(null);
        }).to["throw"]();
        return expect(function() {
          return create(void 0);
        }).to["throw"]();
      });
      it('should throw an error if cfg.tag is neither a not empty string nor a component class', function() {
        expect(function() {
          return create({
            tag: null
          });
        }).to["throw"]();
        expect(function() {
          return create({
            tag: void 0
          });
        }).to["throw"]();
        expect(function() {
          return create({
            tag: ''
          });
        }).to["throw"]();
        expect(function() {
          return create({
            tag: []
          });
        }).to["throw"]();
        expect(function() {
          return create({
            tag: {}
          });
        }).to["throw"]();
        expect(function() {
          return create({
            tag: function() {}
          });
        }).to["throw"]();
        expect(function() {
          return create({
            tag: 'a'
          });
        }).to.not["throw"]();
        expect(function() {
          return create({
            tag: MockNode
          });
        }).to.not["throw"]();
        return expect(function() {
          return create({
            tag: ExtendedMockNode
          });
        }).to.not["throw"]();
      });
      it('should return a text node', function() {
        expectText(create('hello'), 'hello');
        expectText(create(0), 0);
        return expectText(create(true), true);
      });
      it('should return a basic node with given tag', function() {
        return expectTag(create({
          tag: 'hello'
        }), 'hello');
      });
      it('should return a component node', function() {
        expectNode(create({
          tag: MockNode
        }), MockNode);
        return expectTag(create({
          tag: MockNode
        }), 'mock-node');
      });
      return it('should return a mapped node', function() {
        expectNode(create({
          tag: 'mock'
        }), MockNode);
        return expectTag(create({
          tag: MockNode
        }), 'mock-node');
      });
    });
  });

}).call(this);

//# sourceMappingURL=view-tree.js.map
