// Generated by CoffeeScript 1.12.6
(function() {
  module.exports = {
    TreeOne: require('./tree-one'),
    TreeTwo: require('./tree-two')
  };

}).call(this);

//# sourceMappingURL=both-trees.js.map
