// Generated by CoffeeScript 1.12.6
(function() {
  module.exports = {
    ViewTree: require('./view-tree'),
    DataTree: require('./data-tree')
  };

}).call(this);

//# sourceMappingURL=both-trees.js.map
