// Generated by CoffeeScript 1.12.6
(function() {
  var ViewNode, __id__, addChild, append, before, behind, change, checkDom, classMap, cleanMap, create, createTagFromDom, createTagView, createTextFromDom, createTextView, createView, dirty, dirtyMap, disposeNode, domList, extendsNode, getOrCall, injectNode, isBool, isDom, isDomText, isFunc, isNot, isNumber, isObject, isSimple, isString, j, lastTime, len, map, nodeMap, normalizeEvent, normalizeName, rafTimeout, remove, removeChild, removeEvents, render, replace, replaceChild, unmap, update, updateAttr, updateBool, updateChildren, updateClass, updateEvent, updateNow, updateProperties, updateStyle, updateText, vendor, vendors,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    slice = [].slice;

  __id__ = 0;

  getOrCall = function(value) {
    if (isFunc(value)) {
      return value();
    } else {
      return value;
    }
  };

  isBool = function(value) {
    return typeof value === 'boolean';
  };

  isNumber = function(value) {
    return typeof value === 'number';
  };

  isString = function(value) {
    return typeof value === 'string' || value === value + '';
  };

  isObject = function(value) {
    return typeof value === 'object';
  };

  isFunc = function(value) {
    return typeof value === 'function';
  };

  isDom = function(value) {
    return value instanceof HTMLElement;
  };

  isDomText = function(value) {
    return value instanceof Text;
  };

  isNot = function(value) {
    return value === null || value === void 0;
  };

  isSimple = function(value) {
    var t;
    return (t = typeof value) === 'string' || t === 'number' || t === 'boolean';
  };

  extendsNode = function(value) {
    return isFunc(value) && ((value.prototype instanceof ViewNode) || value === ViewNode);
  };

  normalizeName = function(name) {
    return name.replace(/[A-Z]/g, function(name) {
      return '-' + name.toLowerCase();
    });
  };

  normalizeEvent = function(type) {
    type = type.slice(2);
    return type.charAt(0).toLowerCase() + normalizeName(type.slice(1));
  };


  /*
      cfg as string || boolean || number
          node is a text node
  
      cfg as object
          tag can be
              string
                  which is mapped to an component class
                  the node name
              node class
              node instance
  
      cfg as node instance # invalid in create
  
      cfg as func
  
  
      cfg =
          tag:
          text:
          style:
          bind
          clazz:
          child:
          children:
          event handlers starting with 'on', camel case converts to kebab case
  
  
      update:
  
          if value == undefined -> no update
          if value == null      -> remove value
          else                  -> update
   */

  ViewNode = (function() {
    ViewNode.DEBUG = true;

    ViewNode.CHECK_DOM = true;

    ViewNode.DEFAULT_CLASS = ViewNode;

    function ViewNode(cfg) {
      this.update = bind(this.update, this);
      this.register(cfg);
      this.updateCfg(cfg);
      this.updateNow();
    }

    ViewNode.prototype.register = function(cfg1) {
      this.cfg = cfg1;
      this.parent = null;
      this.depth = 0;
      this.keep = false;
      if (!this.__id__) {
        this.__id__ = ++__id__;
        nodeMap[this.__id__] = this;
      }
      this.__id__;
      return injectNode(this, this.cfg);
    };

    ViewNode.prototype.updateNow = function(cfg) {
      cfg = cfg || this.render();
      if (isNot(this.view)) {
        createView(this, cfg);
      }
      if (isSimple(cfg) || (!cfg.tag && (isSimple(cfg.text) || isFunc(cfg.text)))) {
        updateText(this, cfg);
      } else {
        updateProperties(this, cfg);
      }
      return this;
    };

    ViewNode.prototype.appendTo = function(dom) {
      return append(this, dom);
    };

    ViewNode.prototype.behind = function(dom) {
      return behind(this, dom);
    };

    ViewNode.prototype.before = function(dom) {
      return before(this, dom);
    };

    ViewNode.prototype.replace = function(dom) {
      return replace(this, dom);
    };

    ViewNode.prototype.remove = function(dom) {
      return replace(this, dom);
    };

    ViewNode.prototype.dispose = function() {
      return null;
    };

    ViewNode.prototype.onMount = function() {
      return null;
    };

    ViewNode.prototype.onUnmount = function() {
      return this.keep;
    };

    ViewNode.prototype.updateCfg = function(cfg) {
      return (this.cfg = cfg) || true;
    };

    ViewNode.prototype.update = function() {
      return update(this);
    };

    ViewNode.prototype.render = function() {
      return this.cfg;
    };

    ViewNode.prototype.onAdded = function() {};

    ViewNode.prototype.onRemoved = function() {};

    ViewNode.prototype.addChild = function(child) {};

    ViewNode.prototype.addChildAt = function(child, index) {};

    ViewNode.prototype.removeChild = function(child) {};

    ViewNode.prototype.removeChildAt = function(index) {};

    return ViewNode;

  })();

  classMap = {};

  nodeMap = {};

  dirtyMap = {};

  cleanMap = {};

  domList = [];

  dirty = false;

  rafTimeout = null;

  map = function(tag, clazz, overwrite) {
    if (overwrite == null) {
      overwrite = false;
    }
    if (isNot(classMap[tag]) || overwrite) {
      classMap[tag] = clazz;
    }
    return null;
  };

  unmap = function(tag) {
    delete classMap[tag];
    return null;
  };

  create = function(cfg, root) {
    var clazz, node, tag;
    if (root == null) {
      root = null;
    }
    if (isNot(cfg)) {
      throw new Error("A node can't be created from empty cfg.");
    }
    if (!extendsNode(clazz = cfg.clazz)) {
      if (!extendsNode(clazz = cfg.tag)) {
        clazz = null;
        if (isDom(cfg)) {
          tag = cfg.nodeName.toLowerCase();
        }
        if (isString(tag = tag || cfg.tag)) {
          clazz = classMap[tag];
        }
      }
    }
    clazz = clazz || ViewNode.DEFAULT_CLASS;
    node = new clazz(cfg);
    if (root !== null) {
      render(node, root);
    }
    return node;
  };

  injectNode = function(node, cfg) {
    var inject, key, value;
    if (isNot(node.__i__) && cfg && cfg.__i__) {
      inject = node.__i__ = cfg.__i__;
      for (key in inject) {
        value = inject[key];
        node[key] = value;
      }
    }
    return node;
  };

  createView = function(node, cfg) {
    var tag;
    if (node.view) {
      throw new Error("View already exists");
    }
    if (isNot(cfg = node.render())) {
      throw new Error("A view for an empty cfg can't be created.");
    }
    switch (true) {
      case isSimple(cfg):
        createTextView(node, node.cfg = {
          text: cfg + ''
        });
        break;
      case isDom(cfg):
        createTagFromDom(node, null, cfg);
        break;
      case isDomText(cfg):
        createTextFromDom(node, null, cfg);
        break;
      default:
        tag = cfg.tag;
        switch (true) {
          case isNot(tag):
            createTextView(node, cfg);
            break;
          case isString(tag):
            createTagView(node, cfg);
            break;
          case isDom(tag):
            createTagFromDom(node, cfg, tag);
            break;
          case isDomText(tag):
            createTextFromDom(node, cfg, tag);
            break;
          default:
            if (extendsNode(tag)) {
              throw new Error("A tag must be a string or a HTMLElement, you specified a ViewNode class.");
            }
            throw new Error("A tag must be a string or a HTMLElement.");
        }
    }
    if (ViewNode.CHECK_DOM) {
      domList.push(node.view);
    }
    return node;
  };

  createTextView = function(node, cfg) {
    var text;
    text = cfg.text;
    if (isFunc(text)) {
      text = text();
    }
    if (!isSimple(text)) {
      throw new Error("The text for a text node must be a string, number or bool.");
    }
    node.text = text;
    node.tag = cfg.tag = null;
    node.kind = ViewNode.TEXT_KIND;
    return node.view = document.createTextNode(text);
  };

  createTextFromDom = function(node, cfg, dom) {
    var text;
    if (ViewNode.CHECK_DOM) {
      checkDom(dom);
    }
    node.text = dom.nodeValue;
    node.tag = null;
    node.kind = ViewNode.TEXT_KIND;
    node.view = dom;
    if (cfg) {
      text = cfg.text;
      if (isNot(text)) {
        cfg.text = node.text;
      } else {
        if (isFunc(text)) {
          text = text();
        }
        if (!isSimple(text)) {
          throw new Error("The text for a text node must be a string, number or bool.");
        }
        node.text = dom.nodeValue = text;
      }
    } else {
      cfg = node.cfg = {
        text: node.text
      };
    }
    cfg.tag = null;
    return node;
  };

  createTagView = function(node, cfg) {
    var tag;
    node.tag = tag = cfg.tag;
    node.kind = ViewNode.TAG_KIND;
    node.view = document.createElement(tag);
    return node;
  };

  createTagFromDom = function(node, cfg, dom) {
    if (ViewNode.CHECK_DOM) {
      checkDom(dom);
    }
    node.tag = dom.nodeName.toLowerCase();
    node.kind = ViewNode.TAG_KIND;
    node.view = dom;
    cfg = cfg || (node.cfg = {});
    cfg.tag = node.tag;
    return node;
  };

  render = function(node, root) {
    var cfg;
    cfg = node.render();
    if (!node.view) {
      createView(node, cfg);
    }
    root.appendChild(node.view);
    node.updateNow();
    node.onMount();
    return null;
  };

  remove = function(nodeOrRoot) {};

  update = function(node) {
    var id;
    id = node != null ? node.__id__ : void 0;
    if (!id) {
      throw new Error("Can't update node. ViewNode doesn't exist.");
    }
    if (!dirty) {
      window.cancelAnimationFrame(rafTimeout);
      rafTimeout = window.requestAnimationFrame(updateNow);
    }
    dirtyMap[id] = true;
    dirty = true;
    return null;
  };

  updateNow = function() {
    var cfg, id, j, len, n, node, nodes;
    window.cancelAnimationFrame(rafTimeout);
    dirty = false;
    cleanMap = {};
    nodes = [];
    for (id in dirtyMap) {
      if (n = nodeMap[id]) {
        nodes.push(n);
      }
    }
    nodes.sort(function(a, b) {
      return a.depth - b.depth;
    });
    for (j = 0, len = nodes.length; j < len; j++) {
      node = nodes[j];
      if (!node.view || !nodeMap[node.__id__] || cleanMap[node.__id__]) {
        continue;
      }
      cfg = node.render();
      if (isNot(node.tag) && isNot(cfg.tag)) {
        updateText(node, cfg);
      } else if (!(node.tag === cfg.tag || node.constructor === cfg.tag)) {
        replaceChild(node, cfg);
      } else {
        updateProperties(node, cfg);
      }
    }
    dirtyMap = {};
    return null;
  };

  updateText = function(node, cfg) {
    var text;
    cleanMap[node.__id__] = true;
    text = isFunc(cfg.text) ? cfg.text() : isString(cfg) ? cfg : cfg.text;
    if (node.text !== text) {
      node.cfg = cfg;
      node.text = text;
      node.view.nodeValue = text;
    }
    return null;
  };

  updateProperties = function(node, cfg) {
    var attr, attrs, child, name, propMap, text, value;
    cleanMap[node.__id__] = true;
    if (cfg instanceof ViewNode) {
      cfg = cfg.render();
    }
    attrs = node.attrs || (node.attrs = {});
    propMap = Object.assign({}, attrs, node.events, cfg);
    if (propMap.hasOwnProperty('className')) {
      updateClass(node, cfg.className);
    }
    if (propMap.hasOwnProperty('style')) {
      updateStyle(node, cfg.style);
    }
    if (propMap.hasOwnProperty('text')) {
      if (isFunc(text = cfg.text)) {
        text = text();
      }
      if (isSimple(text)) {
        updateChildren(node, [text]);
      } else if (isDomText(text)) {
        updateChildren(node, [text]);
      }
      if (ViewNode.DEBUG) {
        if (cfg.hasOwnProperty('child')) {
          console.warn('child specified while text exists: ', cfg);
        }
        if (cfg.hasOwnProperty('children')) {
          console.warn('children specified while text exists', cfg);
        }
      }
    } else if (propMap.hasOwnProperty('child')) {
      if (isFunc(child = cfg.child)) {
        child = child();
      }
      updateChildren(node, [child]);
      if (ViewNode.DEBUG) {
        if (cfg.hasOwnProperty('children')) {
          console.warn('children specified while text exists', cfg);
        }
      }
    } else if (propMap.hasOwnProperty('children')) {
      updateChildren(node, cfg.children);
    }
    delete propMap.tag;
    delete propMap.clazz;
    delete propMap.__i__;
    delete propMap.keep;
    delete propMap.text;
    delete propMap.child;
    delete propMap.className;
    delete propMap.style;
    delete propMap.children;
    delete propMap.bindings;
    for (name in propMap) {
      attr = attrs[name];
      value = cfg[name];
      if (isBool(value) || (isNot(value) && isBool(attr))) {
        updateBool(node, value, name);
      } else {
        if (/^on/.test(name)) {
          updateEvent(node, value, name);
        } else {
          if (isFunc(value)) {
            value = value();
          }
          if (isBool(value)) {
            updateBool(node, value, name);
          } else {
            updateAttr(node, value, name);
          }
        }
      }
    }
    return null;
  };

  updateAttr = function(node, value, name) {
    var view;
    node.attrs[name] = node.view.getAttribute(name);
    if (node.attrs[name] === value) {
      return;
    }
    view = node.view;
    if (value !== null && value !== void 0) {
      view.setAttribute(name, value);
      view[name] = value;
      node.attrs[name] = value;
    } else {
      view.removeAttribute(name);
      delete view[name];
      delete node.attrs[name];
    }
    return null;
  };

  updateBool = function(node, value, name) {
    var view;
    node.attrs[name] = node.view[name];
    if (node.attrs[name] === value) {
      return;
    }
    view = node.view;
    if (isNot(value)) {
      view.removeAttribute(name);
      view[name] = false;
      delete node.attrs[name];
    } else if (value === false) {
      view.removeAttribute(name);
      view[name] = false;
      node.attrs[name] = false;
    } else {
      view.setAttribute(name, '');
      view[name] = true;
      node.attrs[name] = true;
    }
    return null;
  };

  updateClass = function(node, value) {
    if (isFunc(value)) {
      value = value();
    }
    node.attrs.className = node.view.className;
    if (node.attrs.className === value) {
      return;
    }
    if (value) {
      node.view.className = value;
      node.attrs.className = value;
    } else {
      node.view.className = void 0;
      delete node.attrs.className;
    }
    return null;
  };

  updateStyle = function(node, style) {
    var attrs, changed, css, name, prop, propMap, sobj, value, view;
    view = node.view;
    attrs = node.attrs;
    sobj = attrs.style;
    if (!view) {
      return;
    }
    if (isFunc(style)) {
      style = style();
    }
    if (isNot(style)) {
      view.style.cssText = null;
      delete attrs.style;
    } else if (isString(style)) {
      view.style.cssText = style;
      attrs.style = style;
    } else {
      css = '';
      sobj = isObject(sobj) ? sobj : {};
      changed = false;
      propMap = Object.assign({}, style, sobj);
      for (name in propMap) {
        value = style[name];
        if (value !== sobj[name]) {
          changed = true;
        }
        sobj[name] = value;
        if (isNot(value)) {
          delete sobj[name];
        } else {
          prop = normalizeName(name);
          css += prop + ': ' + value + '; ';
        }
      }
      if (changed) {
        if (css.length) {
          css = css.slice(0, -1);
          view.style.cssText = css;
          attrs.style = sobj;
        } else {
          view.style.cssText = null;
          delete attrs.style;
        }
      }
    }
    return null;
  };

  updateEvent = function(node, callback, name) {
    var events, listener, type, view;
    events = node.events || (node.events = {});
    view = node.view;
    type = normalizeEvent(name);
    listener = events[name];
    if (isString(callback)) {
      callback = node[name];
    }
    if (listener !== callback) {
      if (listener) {
        view.removeEventListener(type, listener);
        delete events[name];
      }
      if (callback) {
        view.addEventListener(type, callback);
        events[name] = callback;
      }
    }
    return null;
  };

  removeEvents = function(node) {
    var events, listener, name, type, view;
    events = node.events;
    if (!events) {
      return null;
    }
    view = node.view;
    for (name in events) {
      listener = events[name];
      type = normalizeEvent(name);
      if (listener) {
        view.removeEventListener(type, listener);
      }
      delete events[name];
    }
    node.events = null;
    return null;
  };

  updateChildren = function(node, cfgs) {
    var cfg, child, children, i, j, l, ref;
    children = node.children || (node.children = []);
    if (isFunc(cfgs)) {
      cfgs = cfgs();
    }
    cfgs = isString(cfgs) ? [cfgs] : cfgs || [];
    l = children.length > cfgs.length ? children.length : cfgs.length;
    for (i = j = 0, ref = l; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      child = children[i];
      cfg = cfgs[i];
      if (isFunc(cfg)) {
        cfg = cfg();
      }
      if (!child && !cfg) {
        throw new Error(("DOM ERROR: either child or cfg at index " + i + " must be defined. Got ") + child + ', ' + cfg);
      }
      if (!child) {
        addChild(node, cfg);
      } else if (!cfg) {
        removeChild(child);
      } else {
        change(child, cfg);
      }
    }
    children.length = cfgs.length;
    return null;
  };

  change = function(node, cfg) {
    var needsUpdate;
    needsUpdate = node.updateCfg(cfg);
    if (node === cfg || node.constructor === cfg.tag) {
      if (needsUpdate) {
        updateProperties(node, node.render());
      }
    } else if (node.tag !== cfg.tag || cfg instanceof ViewNode) {
      replaceChild(node, cfg);
    } else if (isNot(node.tag)) {
      updateText(node, cfg);
    } else if (needsUpdate) {
      updateProperties(node, cfg);
    }
    return false;
  };

  addChild = function(node, cfg) {
    var child;
    if (cfg instanceof ViewNode) {
      child = cfg;
    } else {
      if (!cfg.__i__) {
        cfg.__i__ = node.__i__;
      }
      child = create(cfg);
    }
    node.children.push(child);
    node.view.appendChild(child.view);
    child.parent = node;
    child.depth = node.depth + 1;
    child.onMount();
    return null;
  };

  removeChild = function(child) {
    var node, view;
    node = child.parent;
    view = child.view;
    disposeNode(child);
    node.view.removeChild(view);
    return null;
  };

  replaceChild = function(child, cfg) {
    var children, i, node, view;
    node = child.parent;
    children = node.children;
    i = children.indexOf(child);
    view = child.view;
    disposeNode(child);
    if (cfg instanceof ViewNode) {
      child = cfg;
      cfg = child.render();
    } else {
      if (!cfg.__i__) {
        cfg.__i__ = node.__i__;
      }
      child = create(cfg);
    }
    children[i] = child;
    child.parent = node;
    child.depth = node.depth + 1;
    node.view.replaceChild(child.view, view);
    if (isSimple(cfg) || (!cfg.tag && (isSimple(cfg.text) || isFunc(cfg.text)))) {
      updateText(child, cfg);
    } else {
      updateProperties(child, cfg);
    }
    child.onMount();
    return null;
  };

  disposeNode = function(node) {
    var child, j, len, ref;
    if (node.onUnmount() !== true) {
      removeEvents(node);
      if (node.children && node.children.length) {
        ref = node.children;
        for (j = 0, len = ref.length; j < len; j++) {
          child = ref[j];
          disposeNode(child);
        }
      }
      delete node.children;
      delete node.view;
      delete nodeMap[node.__id__];
    }
    node.parent = null;
    node.depth = void 0;
    return null;
  };

  checkDom = function(dom) {
    if (domList.indexOf(dom) > -1) {
      throw new Error('Dom element already controlled by another node.');
    }
  };

  append = function(node, dom) {
    if (ViewNode.CHECK_DOM) {
      checkDom(dom);
    }
    return dom.appendChild(node.view);
  };

  behind = function(node, dom) {
    var next, parent;
    parent = dom.parentNode;
    next = dom.nextSibling;
    if (ViewNode.CHECK_DOM) {
      checkDom(parent);
    }
    if (next) {
      return parent.insertBefore(node.view, next);
    } else {
      return parent.appendChild(node.view);
    }
  };

  before = function(node, dom) {
    var parent;
    parent = dom.parentNode;
    if (ViewNode.CHECK_DOM) {
      checkDom(parent);
    }
    return parent.insertBefore(node.view, dom);
  };

  replace = function(node, dom) {
    var parent;
    parent = dom.parentNode;
    if (ViewNode.CHECK_DOM) {
      checkDom(parent);
      checkDom(dom);
    }
    return parent.replaceChild(node.view, dom);
  };

  remove = function(node) {
    var parent;
    parent = node.view.parentNode;
    if (ViewNode.CHECK_DOM) {
      checkDom(parent);
    }
    return parent.removeChild(node.view);
  };

  if (typeof window !== 'undefined') {
    lastTime = 0;
    vendors = ['webkit', 'moz'];
    for (j = 0, len = vendors.length; j < len; j++) {
      vendor = vendors[j];
      if (window.requestAnimationFrame) {
        break;
      }
      window.requestAnimationFrame = window[vendor + 'RequestAnimationFrame'];
      window.cancelAnimationFrame = window[vendor + 'CancelAnimationFrame'] || window[vendor + 'CancelRequestAnimationFrame'];
    }
    if (!window.requestAnimationFrame) {
      window.requestAnimationFrame = function(callback) {
        var currTime, id, rAF, timeToCall;
        currTime = Date.now();
        timeToCall = Math.max(0, 16 - currTime + lastTime);
        rAF = function() {
          return callback(currTime + timeToCall);
        };
        id = window.setTimeout(rAF, timeToCall);
        lastTime = currTime + timeToCall;
        return id;
      };
    }
    if (!window.cancelAnimationFrame) {
      window.cancelAnimationFrame = function(id) {
        clearTimeout(id);
        return null;
      };
    }
  }

  if (typeof Object.assign === 'undefined') {
    Object.assign = function() {
      var args, k, key, len1, src, target;
      target = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      for (k = 0, len1 = args.length; k < len1; k++) {
        src = args[k];
        for (key in src) {
          target[key] = src[key];
        }
      }
      return target;
    };
  }

  ViewNode.create = create;

  ViewNode.map = map;

  ViewNode.unmap = unmap;

  ViewNode.append = append;

  ViewNode.behind = behind;

  ViewNode.before = before;

  ViewNode.replace = replace;

  ViewNode.remove = remove;

  ViewNode.getOrCall = getOrCall;

  ViewNode.isBool = isBool;

  ViewNode.isNumber = isNumber;

  ViewNode.isString = isString;

  ViewNode.isObject = isObject;

  ViewNode.isFunc = isFunc;

  ViewNode.isDom = isDom;

  ViewNode.isDomText = isDomText;

  ViewNode.isNot = isNot;

  ViewNode.isSimple = isSimple;

  ViewNode.extendsNode = extendsNode;

  if (typeof module !== 'undefined') {
    module.exports = ViewNode;
  }

  if (typeof window !== 'undefined') {
    window.ViewNode = ViewNode;
  } else {
    this.ViewNode = ViewNode;
  }

}).call(this);

//# sourceMappingURL=view-node.js.map
