// Generated by CoffeeScript 1.12.6
(function() {
  var COMP_CFG_ERROR, NODE_KIND, Node, TEXT_KIND, VIEW_CFG_ERROR, ViewTree, __id__, addChild, append, before, behind, change, checkDom, cleanMap, create, createNode, createView, dirty, dirtyMap, disposeNode, domList, getCfgJson, injectNode, isBool, isFunc, isHTML, isNot, isNumber, isObject, isSimple, isString, j, lastTime, len, map, nodeMap, normalizeEvent, normalizeName, rafTimeout, remove, removeChild, removeEvents, render, replace, replaceChild, tagMap, throwNodeCfgError, throwViewCfgError, unmap, update, updateAttr, updateBool, updateChildren, updateClass, updateEvent, updateNow, updateProperties, updateStyle, updateText, vendor, vendors,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    slice = [].slice;

  __id__ = 0;

  TEXT_KIND = 0;

  NODE_KIND = 1;

  COMP_CFG_ERROR = 'Cfg for creating a node must either be a string or an object containing a tag property as not empty string or a node class.';

  VIEW_CFG_ERROR = 'Cfg for creating a view must either be a string or an object containing a tag property as not empty string';

  isBool = function(value) {
    return typeof value === 'boolean';
  };

  isNumber = function(value) {
    return typeof value === 'number';
  };

  isString = function(value) {
    return typeof value === 'string' || value === value + '';
  };

  isObject = function(value) {
    return typeof value === 'object';
  };

  isFunc = function(value) {
    return typeof value === 'function';
  };

  isHTML = function(value) {
    return value instanceof HTMLElement;
  };

  isNot = function(value) {
    return value === null || value === void 0;
  };

  isSimple = function(value) {
    var t;
    return (t = typeof value) === 'string' || t === 'number' || t === 'boolean';
  };

  normalizeName = function(name) {
    return name.replace(/[A-Z]/g, function(name) {
      return '-' + name.toLowerCase();
    });
  };

  normalizeEvent = function(type) {
    type = type.slice(2);
    return type.charAt(0).toLowerCase() + normalizeName(type.slice(1));
  };

  throwNodeCfgError = function(cfg) {
    throw new Error(COMP_CFG_ERROR + ' cfg = ' + getCfgJson(cfg));
  };

  throwViewCfgError = function(cfg) {
    throw new Error(VIEW_CFG_ERROR + ' cfg = ' + getCfgJson(cfg));
  };

  getCfgJson = function(cfg) {
    var c;
    try {
      c = JSON.stringify(cfg);
    } catch (error) {

    }
    return c + '';
  };


  /*
      cfg as string || boolean || number
          node is a text node
  
      cfg as object
          tag can be
              string
                  which is mapped to an component class
                  the node name
              node class
              node instance
  
      cfg as node instance # invalid in create
  
      cfg as func
  
  
      cfg =
          tag:
          text:
          style:
          bind
          clazz:
          child:
          children:
          event handlers starting with 'on', camel case converts to kebab case
  
  
      update:
  
          if value == undefined -> no update
          if value == null      -> remove value
          else                  -> update
   */

  Node = (function() {
    Node.DEBUG = true;

    Node.CHECK_DOM = true;

    function Node(cfg) {
      this.update = bind(this.update, this);
      this.register(cfg);
    }

    Node.prototype.register = function(cfg1) {
      this.cfg = cfg1;
      this.keep = false;
      if (!this.__id__) {
        this.__id__ = ++__id__;
        nodeMap[this.__id__] = this;
      }
      this.__id__;
      return injectNode(this, this.cfg);
    };

    Node.prototype.updateNow = function() {
      var cfg;
      cfg = this.render();
      if (!this.view) {
        createView(this, cfg);
      }
      if (isSimple(cfg) || (!cfg.tag && (isSimple(cfg.text) || isFunc(cfg.text)))) {
        return updateText(this, cfg);
      } else {
        return updateProperties(this, cfg);
      }
    };

    Node.prototype.appendTo = function(dom) {
      if (!this.view) {
        this.updateNow();
      }
      return append(this, dom);
    };

    Node.prototype.behind = function(dom) {
      if (!this.view) {
        this.updateNow();
      }
      return behind(this, dom);
    };

    Node.prototype.before = function(dom) {
      if (!this.view) {
        this.updateNow();
      }
      return before(this, dom);
    };

    Node.prototype.replace = function(dom) {
      if (!this.view) {
        this.updateNow();
      }
      return replace(this, dom);
    };

    Node.prototype.dispose = function() {
      return null;
    };

    Node.prototype.onMount = function() {
      return null;
    };

    Node.prototype.onUnmount = function() {
      return this.keep;
    };

    Node.prototype.needsUpdate = function() {
      return true;
    };

    Node.prototype.canUpdate = function(cfg1) {
      this.cfg = cfg1;
      return true;
    };

    Node.prototype.update = function() {
      return update(this);
    };

    Node.prototype.render = function() {
      return this.cfg;
    };

    Node.prototype.onAdded = function() {};

    Node.prototype.onRemoved = function() {};

    Node.prototype.add = function(child) {};

    Node.prototype.addAt = function(child, index) {};

    Node.prototype.remove = function(child) {};

    Node.prototype.removeAt = function(index) {};

    return Node;

  })();

  tagMap = {};

  nodeMap = {};

  dirtyMap = {};

  cleanMap = {};

  domList = [];

  dirty = false;

  rafTimeout = null;

  map = function(tag, clazz, overwrite) {
    if (overwrite == null) {
      overwrite = false;
    }
    if (isNot(tagMap[tag]) || overwrite) {
      tagMap[tag] = clazz;
    }
    return null;
  };

  unmap = function(tag) {
    delete tagMap[tag];
    return null;
  };

  create = function(cfg, root) {
    var clazz, node, tag;
    if (root == null) {
      root = null;
    }
    if (isNot(cfg)) {
      throwNodeCfgError(cfg);
    }
    tag = cfg.tag;
    if (isSimple(cfg) || (!tag && (isSimple(cfg.text) || isFunc(cfg.text)))) {
      clazz = ViewTree.DEFAULT_CLASS;
    } else {
      if (isFunc(tag) && ((tag.prototype instanceof Node) || tag === Node)) {
        clazz = cfg.tag;
      } else {
        if (!isString(tag) || tag === '') {
          throwNodeCfgError(cfg);
        }
        clazz = tagMap[tag] || ViewTree.DEFAULT_CLASS;
      }
    }
    node = new clazz(cfg);
    createView(node, node.render());
    if (root !== null) {
      render(node, root);
    }
    return node;
  };

  createNode = function(clazz, cfg, inject) {
    var key, m, node, p, value;
    inject = cfg.__i__ || inject;
    if (!inject) {
      return new clazz(cfg);
    }
    p = clazz.prototype;
    m = {};
    for (key in inject) {
      value = inject[key];
      m[key] = p[key];
      p[key] = value;
    }
    node = new clazz(cfg);
    node.__i__ = inject;
    for (key in inject) {
      value = inject[key];
      node[key] = value;
      p[key] = m[key];
    }
    return node;
  };

  injectNode = function(node, cfg) {
    var inject, key, value;
    if (isNot(node.__i__) && cfg && cfg.__i__) {
      inject = node.__i__ = cfg.__i__;
      for (key in inject) {
        value = inject[key];
        node[key] = value;
      }
    }
    return node;
  };

  createView = function(node, cfg) {
    var tag, text;
    if (isNot(cfg)) {
      throwViewCfgError(cfg);
    }
    text = isFunc(cfg.text) ? cfg.text() : cfg.text;
    if (isSimple(cfg) || (!cfg.tag && (isSimple(text)))) {
      node.tag = void 0;
      node.text = isNot(text) ? cfg : text;
      node.view = document.createTextNode(node.text);
    } else {
      if (!isString(tag = cfg.tag) || tag === '') {
        throwViewCfgError(cfg);
      }
      node.tag = tag;
      node.view = document.createElement(tag);
    }
    return node.view;
  };

  render = function(node, root) {
    var cfg;
    cfg = node.render();
    if (!node.view) {
      createView(node, cfg);
    }
    root.appendChild(node.view);
    node.parent = null;
    node.depth = 0;
    if (isSimple(cfg) || isNot(cfg.tag)) {
      updateText(node, cfg);
    } else {
      updateProperties(node, cfg);
    }
    node.onMount();
    return null;
  };

  remove = function(nodeOrRoot) {};

  update = function(node) {
    var id;
    id = node != null ? node.__id__ : void 0;
    if (!id) {
      throw new Error("DOM ERROR: can't update node. Node doesn't exist. cfg = " + getCfgJson((node != null ? node.cfg : void 0) || null));
    }
    if (!dirty) {
      window.cancelAnimationFrame(rafTimeout);
      rafTimeout = window.requestAnimationFrame(updateNow);
    }
    dirtyMap[id] = true;
    dirty = true;
    return null;
  };

  updateNow = function() {
    var cfg, id, j, len, n, node, nodes;
    window.cancelAnimationFrame(rafTimeout);
    dirty = false;
    cleanMap = {};
    nodes = [];
    for (id in dirtyMap) {
      if (n = nodeMap[id]) {
        nodes.push(n);
      }
    }
    nodes.sort(function(a, b) {
      return a.depth - b.depth;
    });
    for (j = 0, len = nodes.length; j < len; j++) {
      node = nodes[j];
      if (!node.view || !nodeMap[node.__id__] || cleanMap[node.__id__]) {
        continue;
      }
      cfg = node.render();
      if (isNot(node.tag) && isNot(cfg.tag)) {
        updateText(node, cfg);
      } else if (!(node.tag === cfg.tag || node.constructor === cfg.tag)) {
        replaceChild(node, cfg);
      } else {
        updateProperties(node, cfg);
      }
    }
    dirtyMap = {};
    return null;
  };

  updateText = function(node, cfg) {
    var text;
    cleanMap[node.__id__] = true;
    text = isFunc(cfg.text) ? cfg.text() : isString(cfg) ? cfg : cfg.text;
    if (node.text !== text) {
      node.cfg = cfg;
      node.text = text;
      node.view.nodeValue = text;
    }
    return null;
  };

  updateProperties = function(node, cfg) {
    var attr, attrs, child, name, propMap, text, value;
    cleanMap[node.__id__] = true;
    if (cfg instanceof Node) {
      cfg = cfg.render();
    }
    attrs = node.attrs || (node.attrs = {});
    propMap = Object.assign({}, attrs, node.events, cfg);
    if (propMap.hasOwnProperty('className')) {
      updateClass(node, cfg.className);
    }
    if (propMap.hasOwnProperty('style')) {
      updateStyle(node, cfg.style);
    }
    if (propMap.hasOwnProperty('text')) {
      if (isFunc(text = cfg.text)) {
        text = text();
      }
      if (isSimple(text)) {
        updateChildren(node, [text]);
      }
      if (Node.DEBUG) {
        if (cfg.hasOwnProperty('child')) {
          console.warn('child specified while text exists: ', cfg);
        }
        if (cfg.hasOwnProperty('children')) {
          console.warn('children specified while text exists', cfg);
        }
      }
    } else if (propMap.hasOwnProperty('child')) {
      if (isFunc(child = cfg.child)) {
        child = child();
      }
      updateChildren(node, [child]);
      if (Node.DEBUG) {
        if (cfg.hasOwnProperty('children')) {
          console.warn('children specified while text exists', cfg);
        }
      }
    } else if (propMap.hasOwnProperty('children')) {
      updateChildren(node, cfg.children);
    }
    delete propMap.tag;
    delete propMap.__i__;
    delete propMap.keep;
    delete propMap.text;
    delete propMap.className;
    delete propMap.style;
    delete propMap.children;
    delete propMap.bindings;
    for (name in propMap) {
      attr = attrs[name];
      value = cfg[name];
      if (isBool(value) || (isNot(value) && isBool(attr))) {
        updateBool(node, value, name);
      } else {
        if (/^on/.test(name)) {
          updateEvent(node, value, name);
        } else {
          if (isFunc(value)) {
            value = value();
          }
          if (isBool(value)) {
            updateBool(node, value, name);
          } else {
            updateAttr(node, value, name);
          }
        }
      }
    }
    return null;
  };

  updateAttr = function(node, value, name) {
    var view;
    node.attrs[name] = node.view.getAttribute(name);
    if (node.attrs[name] === value) {
      return;
    }
    view = node.view;
    if (value !== null && value !== void 0) {
      view.setAttribute(name, value);
      view[name] = value;
      node.attrs[name] = value;
    } else {
      view.removeAttribute(name);
      delete view[name];
      delete node.attrs[name];
    }
    return null;
  };

  updateBool = function(node, value, name) {
    var view;
    node.attrs[name] = node.view[name];
    if (node.attrs[name] === value) {
      return;
    }
    view = node.view;
    if (isNot(value) || value === false) {
      view.removeAttribute(name);
      view[name] = false;
      delete node.attrs[name];
    } else {
      view.setAttribute(name, '');
      view[name] = true;
      node.attrs[name] = true;
    }
    return null;
  };

  updateClass = function(node, value) {
    if (isFunc(value)) {
      value = value();
    }
    node.attrs.className = node.view.className;
    if (node.attrs.className === value) {
      return;
    }
    if (value) {
      node.view.className = value;
      node.attrs.className = value;
    } else {
      node.view.className = void 0;
      delete node.attrs.className;
    }
    return null;
  };

  updateStyle = function(node, style) {
    var attrs, changed, css, name, prop, propMap, sobj, value, view;
    view = node.view;
    attrs = node.attrs;
    sobj = attrs.style;
    if (!view) {
      return;
    }
    if (isFunc(style)) {
      style = style();
    }
    if (isNot(style)) {
      view.style.cssText = null;
      delete attrs.style;
    } else if (isString(style)) {
      view.style.cssText = style;
      attrs.style = style;
    } else {
      css = '';
      sobj = isObject(sobj) ? sobj : {};
      changed = false;
      propMap = Object.assign({}, style, sobj);
      for (name in propMap) {
        value = style[name];
        if (value !== sobj[name]) {
          changed = true;
        }
        sobj[name] = value;
        if (isNot(value)) {
          delete sobj[name];
        } else {
          prop = normalizeName(name);
          css += prop + ': ' + value + '; ';
        }
      }
      if (changed) {
        if (css.length) {
          css = css.slice(0, -1);
          view.style.cssText = css;
          attrs.style = sobj;
        } else {
          view.style.cssText = null;
          delete attrs.style;
        }
      }
    }
    return null;
  };

  updateEvent = function(node, callback, name) {
    var events, listener, type, view;
    events = node.events || (node.events = {});
    view = node.view;
    type = normalizeEvent(name);
    listener = events[name];
    if (isString(callback)) {
      callback = node[name];
    }
    if (listener !== callback) {
      if (listener) {
        view.removeEventListener(type, listener);
        delete events[name];
      }
      if (callback) {
        view.addEventListener(type, callback);
        events[name] = callback;
      }
    }
    return null;
  };

  removeEvents = function(node) {
    var events, listener, name, type, view;
    events = node.events;
    if (!events) {
      return null;
    }
    view = node.view;
    for (name in events) {
      listener = events[name];
      type = normalizeEvent(name);
      if (listener) {
        view.removeEventListener(type, listener);
      }
      delete events[name];
    }
    node.events = null;
    return null;
  };

  updateChildren = function(node, cfgs) {
    var cfg, child, children, i, j, l, ref;
    children = node.children || (node.children = []);
    if (isFunc(cfgs)) {
      cfgs = cfgs();
    }
    cfgs = isString(cfgs) ? [cfgs] : cfgs || [];
    l = children.length > cfgs.length ? children.length : cfgs.length;
    for (i = j = 0, ref = l; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      child = children[i];
      cfg = cfgs[i];
      if (isFunc(cfg)) {
        cfg = cfg();
      }
      if (!child && !cfg) {
        throw new Error(("DOM ERROR: either child or cfg at index " + i + " must be defined. Got ") + child + ', ' + cfg);
      }
      if (!child) {
        addChild(node, cfg);
      } else if (!cfg) {
        removeChild(child);
      } else {
        change(child, cfg);
      }
    }
    children.length = cfgs.length;
    return null;
  };

  change = function(node, cfg) {
    var canUpdate, needsUpdate;
    needsUpdate = node.needsUpdate();
    canUpdate = node.canUpdate(cfg);
    if (node === cfg || node.constructor === cfg.tag) {
      if (needsUpdate && canUpdate) {
        updateProperties(node, node.render());
      }
      if (needsUpdate && !canUpdate) {
        replaceChild(node, node.render());
      }
    } else if (node.tag !== cfg.tag || cfg instanceof Node) {
      replaceChild(node, cfg);
    } else if (node.tag === void 0) {
      updateText(node, cfg);
    } else if (needsUpdate && canUpdate) {
      updateProperties(node, cfg);
    }
    return false;
  };

  addChild = function(node, cfg) {
    var child;
    if (cfg instanceof Node) {
      child = cfg;
    } else {
      if (!cfg.__i__) {
        cfg.__i__ = node.__i__;
      }
      child = create(cfg);
    }
    cfg = child.render();
    if (!child.view) {
      child.view = createView(child, cfg);
    }
    node.children.push(child);
    node.view.appendChild(child.view);
    child.parent = node;
    child.depth = node.depth + 1;
    if (isSimple(cfg) || (!cfg.tag && (isSimple(cfg.text) || isFunc(cfg.text)))) {
      updateText(child, cfg);
    } else {
      updateProperties(child, cfg);
    }
    child.onMount();
    return null;
  };

  removeChild = function(child) {
    var node, view;
    node = child.parent;
    view = child.view;
    disposeNode(child);
    node.view.removeChild(view);
    return null;
  };

  replaceChild = function(child, cfg) {
    var children, i, node, view;
    node = child.parent;
    children = node.children;
    i = children.indexOf(child);
    view = child.view;
    disposeNode(child);
    if (cfg instanceof Node) {
      child = cfg;
      cfg = child.render();
    } else {
      if (!cfg.__i__) {
        cfg.__i__ = node.__i__;
      }
      child = create(cfg);
    }
    cfg = child.render();
    if (!child.view) {
      child.view = createView(child, cfg);
    }
    children[i] = child;
    child.parent = node;
    child.depth = node.depth + 1;
    node.view.replaceChild(child.view, view);
    if (isSimple(cfg) || (!cfg.tag && (isSimple(cfg.text) || isFunc(cfg.text)))) {
      updateText(child, cfg);
    } else {
      updateProperties(child, cfg);
    }
    child.onMount();
    return null;
  };

  disposeNode = function(node) {
    var child, j, len, ref;
    if (node.onUnmount() !== true) {
      removeEvents(node);
      if (node.children && node.children.length) {
        ref = node.children;
        for (j = 0, len = ref.length; j < len; j++) {
          child = ref[j];
          disposeNode(child);
        }
      }
      delete node.children;
      delete node.view;
      delete nodeMap[node.__id__];
    }
    node.parent = null;
    node.depth = void 0;
    return null;
  };

  checkDom = function(dom) {
    if (domList.indexOf(dom) > -1) {
      throw new Error('Dom element already controlled by another node.');
    }
  };

  append = function(node, dom) {
    if (Node.CHECK_DOM) {
      checkDom(dom);
    }
    return dom.appendChild(node.view);
  };

  behind = function(node, dom) {
    var next, parent;
    parent = dom.parentNode;
    next = dom.nextSibling;
    if (Node.CHECK_DOM) {
      checkDom(parent);
    }
    if (next) {
      return parent.insertBefore(node.view, next);
    } else {
      return parent.appendChild(node.view);
    }
  };

  before = function(node, dom) {
    var parent;
    parent = dom.parentNode;
    if (Node.CHECK_DOM) {
      checkDom(parent);
    }
    return parent.insertBefore(node.view, dom);
  };

  replace = function(node, dom) {
    var parent;
    parent = dom.parentNode;
    if (Node.CHECK_DOM) {
      checkDom(parent);
      checkDom(dom);
    }
    return parent.replaceChild(node.view, dom);
  };

  remove = function(node) {
    var parent;
    parent = node.view.parentNode;
    if (Node.CHECK_DOM) {
      checkDom(parent);
    }
    return parent.removeChild(node.view);
  };

  if (typeof window !== 'undefined') {
    lastTime = 0;
    vendors = ['webkit', 'moz'];
    for (j = 0, len = vendors.length; j < len; j++) {
      vendor = vendors[j];
      if (window.requestAnimationFrame) {
        break;
      }
      window.requestAnimationFrame = window[vendor + 'RequestAnimationFrame'];
      window.cancelAnimationFrame = window[vendor + 'CancelAnimationFrame'] || window[vendor + 'CancelRequestAnimationFrame'];
    }
    if (!window.requestAnimationFrame) {
      window.requestAnimationFrame = function(callback) {
        var currTime, id, rAF, timeToCall;
        currTime = Date.now();
        timeToCall = Math.max(0, 16 - currTime + lastTime);
        rAF = function() {
          return callback(currTime + timeToCall);
        };
        id = window.setTimeout(rAF, timeToCall);
        lastTime = currTime + timeToCall;
        return id;
      };
    }
    if (!window.cancelAnimationFrame) {
      window.cancelAnimationFrame = function(id) {
        clearTimeout(id);
        return null;
      };
    }
  }

  if (typeof Object.assign === 'undefined') {
    Object.assign = function() {
      var args, k, key, len1, src, target;
      target = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      for (k = 0, len1 = args.length; k < len1; k++) {
        src = args[k];
        for (key in src) {
          target[key] = src[key];
        }
      }
      return target;
    };
  }

  ViewTree = {
    Node: Node,
    DEFAULT_CLASS: Node,
    HANDLE_CTX: true,
    HANDLE_DATA_TREE: true,
    COMP_CFG_ERROR: COMP_CFG_ERROR,
    VIEW_CFG_ERROR: VIEW_CFG_ERROR,
    map: map,
    unmap: unmap,
    create: create,
    render: render,
    remove: remove,
    update: update,
    updateNow: updateNow
  };

  if (typeof module !== 'undefined') {
    module.exports = ViewTree;
  }

  if (typeof window !== 'undefined') {
    window.ViewTree = ViewTree;
  } else {
    this.ViewTree = ViewTree;
  }

}).call(this);

//# sourceMappingURL=view-tree.js.map
