// Generated by CoffeeScript 1.12.6
(function() {
  var AppView, ViewTree,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ViewTree = require('../../src/js/view-tree');

  AppView = (function(superClass) {
    extend(AppView, superClass);

    function AppView(cfg) {
      this.redo = bind(this.redo, this);
      this.undo = bind(this.undo, this);
      this.onClick = bind(this.onClick, this);
      AppView.__super__.constructor.call(this, cfg);
      this.model = cfg.model;
      this.data = cfg.model.root;
      this.title = this.data.title;
    }

    AppView.prototype.onClick = function() {
      this.data.bgGreen = (Math.random() * 200 + 55) >> 0;
      this.data.title = this.title + '!!!!!'.slice((Math.random() * 5) >> 0);
      this.model.update();
      this.update();
      return null;
    };

    AppView.prototype.undo = function() {
      this.model.undo();
      return this.update();
    };

    AppView.prototype.redo = function() {
      this.model.redo();
      return this.update();
    };

    AppView.prototype.render = function() {
      return {
        tag: 'div',
        children: [
          {
            tag: 'h1',
            title: 'page title',
            className: 'my-class',
            style: "background-color: rgb(0," + this.data.bgGreen + ",0);",
            onClick: this.onClick,
            children: [
              {
                tag: 'span',
                children: this.data.title
              }
            ]
          }, {
            tag: 'button',
            onClick: this.undo,
            children: 'undo'
          }, {
            tag: 'button',
            onClick: this.redo,
            children: 'redo'
          }
        ]
      };
    };

    return AppView;

  })(ViewTree.Node);

  module.exports = AppView;

}).call(this);

//# sourceMappingURL=app-view.js.map
