// Generated by CoffeeScript 1.12.6
(function() {
  var AppView, Context, DataTree, ViewTree;

  ViewTree = require('../../src/js/view-tree');

  DataTree = require('../../src/js/data-tree');

  AppView = require('./app-view');

  Context = (function() {
    function Context() {
      var app, model;
      model = new DataTree({
        title: 'hello two-trees!',
        bgGreen: 255
      });
      app = new AppView({
        tag: AppView,
        model: model
      });
      ViewTree.render(app, document.querySelector('.app'));
    }

    return Context;

  })();

  module.exports = new Context();

}).call(this);

//# sourceMappingURL=context.js.map
