// Generated by CoffeeScript 1.12.6
(function() {
  var AppView, Context, DataTree, ViewTree;

  ViewTree = require('../../src/js/view-tree');

  DataTree = require('../../src/js/data-tree');

  AppView = require('./app-view');

  Context = (function() {
    function Context() {
      var app, model;
      console.log(';-)');
      model = new DataTree({
        title: 'Hello two-trees',
        bgGreen: 255
      });
      app = new AppView({
        model: model
      });
      ViewTree.render(app, document.querySelector('.app'));

      /*
      Treedom.map 'app', AppView
      Treedom.create tag: 'app'
      Treedom.create 'Hello Text Node'
      Treedom.create
          tag: 'h1'
          children: 'Hello H1 Node'
      
      
      test = require 'es6-promise!./test'
      test().then (result) ->
          console.log 'test exports: ', result
       */
    }

    return Context;

  })();

  module.exports = new Context();

}).call(this);

//# sourceMappingURL=context.js.map
